### ISSUE TITLE
iodist.js as no method 'map'

### ISSUE THREAD

**Issue by gschora** [marcelklehr/iodist#5]
So I've cloned iodist, set all the path and other variables but
running 'iodist selfupdate' results in an error:

This is on Win7 x64....
```
C:\Proggis\PortableApps\iodist\lib\iodist.js:120
    .map(function(v){
     ^
TypeError: Object [
{"version":"v1.6.2","date":"2015-03-23","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.7.1","v8":"4.1.0.25","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1m","modules":"42"},
{"version":"v1.6.1","date":"2015-03-20","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.7.1","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1m","modules":"42"},
{"version":"v1.6.0","date":"2015-03-20","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.7.1","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1m","modules":"42"},
{"version":"v1.5.1","date":"2015-03-09","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.7.0","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.5.0","date":"2015-03-06","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.7.0","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.4.3","date":"2015-03-03","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.6.1","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.4.2","date":"2015-02-28","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.6.1","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.4.1","date":"2015-02-27","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.6.0","v8":"4.1.0.21","uv":"1.4.2","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.3.0","date":"2015-02-20","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.5.1","v8":"4.1.0.14","uv":"1.4.0","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.2.0","date":"2015-02-11","files":["linux-armv6l","linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":
"2.5.1","v8":"4.1.0.14","uv":"1.4.0","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.1.0","date":"2015-02-03","files":["linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":"2.4.1","v8":"4
.1.0.14","uv":"1.3.0","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.0.4","date":"2015-01-24","files":["linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":"2.3.0","v8":"4
.1.0.12","uv":"1.2.1","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.0.3","date":"2015-01-20","files":["linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":"2.2.0","v8":"4
.1.0.7","uv":"1.2.1","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.0.2","date":"2015-01-16","files":["linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":"2.1.18","v8":"
3.31.74.1","uv":"1.2.1","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.0.1","date":"2015-01-14","files":["linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":"2.1.18","v8":"
3.31.74.1","uv":"1.2.0","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"},
{"version":"v1.0.0","date":"2015-01-14","files":["linux-armv7l","linux-x64","linux-x86","osx-x64-tar","win-x64-exe","win-x64-msi","win-x86-exe","win-x86-msi"],"npm":"2.1.18","v8":"
3.31.74.1","uv":"1.2.0","zlib":"1.2.8","openssl":"1.0.1k","modules":"42"}
]
 has no method 'map'
    at Request.iodist.listAvailable [as _callback] (C:\Proggis\PortableApps\iodist\lib\iodist.js:120:6)
    at Request.init.self.callback (C:\Proggis\PortableApps\iodist\node_modules\request\main.js:120:22)
    at Request.EventEmitter.emit (events.js:91:17)
    at Request.<anonymous> (C:\Proggis\PortableApps\iodist\node_modules\request\main.js:555:16)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (C:\Proggis\PortableApps\iodist\node_modules\request\main.js:517:14)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1366:20)
Der Befehl "node" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Update dependencies...
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/vows
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/vows
npm http GET https://registry.npmjs.org/glob/4.5.3
npm http GET https://registry.npmjs.org/request/2.9.203
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/vows/0.9.0-rc2
npm http 304 https://registry.npmjs.org/request/2.9.203
npm http 304 https://registry.npmjs.org/vows/0.9.0-rc2
npm http 200 https://registry.npmjs.org/glob/4.5.3
npm http GET https://registry.npmjs.org/glob/-/glob-4.5.3.tgz
request@2.9.203 node_modules\request
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/diff
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm http 200 https://registry.npmjs.org/glob/-/glob-4.5.3.tgz
mkdirp@0.3.5 node_modules\mkdirp
npm http 304 https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/diff
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
vows@0.9.0-rc2 node_modules\vows
├── diff@1.2.2
├── eyes@0.1.8
└── glob@4.3.5 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)
glob@4.5.3 node_modules\rimraf\node_modules\glob
├── inherits@2.0.1
├── inflight@1.0.4 (wrappy@1.0.1)
├── once@1.3.1 (wrappy@1.0.1)
└── minimatch@2.0.4 (brace-expansion@1.1.0)

```

**Comment by marcelklehr** [comment]
Should be fixed now. Thanks for reporting.
